In [3]:
import numpy as np

In [2]:
lst_1=[1,2,3,4,5]

In [20]:
arr1=np.array(lst_1)

If we are giving the same type in the list then it will be correct -> arr2

if we are giving a list with all datatypes it will be overridden with str type -> arr1

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.random.random((2,3))

array([[0.88869863, 0.94470067, 0.07468558],
       [0.84213924, 0.17325621, 0.82882517]])

In [8]:
lst_2=[1,1.0,'Phani']

In [9]:
lst_2

[1, 1.0, 'Phani']

In [15]:
arr2=np.array(lst_2)

In [16]:
arr2

array(['1', '1.0', 'Phani'], dtype='<U32')

In [19]:
type(arr2[0])

numpy.str_

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
type(arr1[0])

numpy.int32

In [25]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
np.arange(10,25,3)

array([10, 13, 16, 19, 22])

In [27]:
np.linspace(10,25,5)

array([10.  , 13.75, 17.5 , 21.25, 25.  ])

In [29]:
np.arange(10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
np.linspace(10,25)

array([10.        , 10.30612245, 10.6122449 , 10.91836735, 11.2244898 ,
       11.53061224, 11.83673469, 12.14285714, 12.44897959, 12.75510204,
       13.06122449, 13.36734694, 13.67346939, 13.97959184, 14.28571429,
       14.59183673, 14.89795918, 15.20408163, 15.51020408, 15.81632653,
       16.12244898, 16.42857143, 16.73469388, 17.04081633, 17.34693878,
       17.65306122, 17.95918367, 18.26530612, 18.57142857, 18.87755102,
       19.18367347, 19.48979592, 19.79591837, 20.10204082, 20.40816327,
       20.71428571, 21.02040816, 21.32653061, 21.63265306, 21.93877551,
       22.24489796, 22.55102041, 22.85714286, 23.16326531, 23.46938776,
       23.7755102 , 24.08163265, 24.3877551 , 24.69387755, 25.        ])

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
arr1.shape

(5,)

In [36]:
arr2

array(['1', '1.0', 'Phani'], dtype='<U32')

In [37]:
arr2.shape

(3,)

In [38]:
a=np.array([[1,2,3],[1,2,3]])

In [39]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [40]:
a.size

6

In [42]:
arr1.ndim

1

In [43]:
arr2.ndim

1

In [44]:
a.ndim

2

In [52]:
ab=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [53]:
ab.ndim

3

In [54]:
ab.dtype

dtype('int32')

In [55]:
arr2.dtype

dtype('<U32')

In [58]:
a.reshape(3,2)

array([[1, 2],
       [3, 1],
       [2, 3]])

In [59]:
np.sum(arr1)

15

In [60]:
arr1

array([1, 2, 3, 4, 5])

In [65]:
np.subtract(arr1,1)

array([0, 1, 2, 3, 4])

In [66]:
np.divide(arr1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [67]:
np.multiply(arr1,10)

array([10, 20, 30, 40, 50])

In [68]:
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [69]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [70]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [71]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [73]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [74]:
np.sum(a)

12

In [75]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [83]:
np.sum([[10,20],[30,40]],axis=1)

array([30, 70])

In [82]:
np.sum([[10,20],[30,40]],axis=0)

array([40, 60])

In [7]:
a1=[10,20]
a2=[20,10]
a3=[10,20]

In [8]:
np.equal(a1,a2)

array([False, False])

In [9]:
np.equal(a1,a3)

array([ True,  True])

In [10]:
np.array_equal(a1,a2)

False

In [11]:
np.array_equal(a1,a3)

True

In [12]:
print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.median(a1))
print(np.var(a1))
print(np.std(a1))

10
20
15.0
15.0
25.0
5.0


In [13]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [16]:
ar[0:2,0:1]

array([[1],
       [4]])

In [17]:
ar[0:1,0:1]

array([[1]])

In [18]:
str1='Python'

In [20]:
str1[1:3]

'yt'

In [26]:
abc=[10,20,30]
de=[40,50,60]

In [28]:
print(abc)
de

[10, 20, 30]


[40, 50, 60]

In [30]:
np.concatenate((abc,de),axis=0)

array([10, 20, 30, 40, 50, 60])

In [32]:
np.vstack((abc,de))

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
np.hstack((abc,de))

array([10, 20, 30, 40, 50, 60])

In [34]:
np.column_stack((abc,de))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [41]:
aaa=np.arange(16).reshape(8,2)

In [43]:
np.hsplit(aaa,2)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15]])]